places/urls.py
from django.urls import path

from places import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('places/new', views.NewPlaceView.as_view(), name='new_place'),
    path('places/<int:pk>', views.PlaceDetail.as_view(), name='place_detail'),
    path('places/<int:pk>/edit', views.PlaceEdit.as_view(), name='place_edit'),
    path('feedback/<int:pk>/new', views.NewFeedBackView.as_view(), name='new_feedback'),
    path('feedback/<int:pk>/moderate', views.FeedbackApprove.as_view(), name='moderate_feedback'),
    path('coupons/', views.CouponList.as_view(), name='coupons'),
    path('coupons/add/', views.NewCoupon.as_view(), name='new_coupon'),
    path('json_places/', views.PlacesAPIView.as_view(), name='user_places'),
    path('json_places/<int:pk>', views.PlacesAPIView.as_view(), name='user_places_detail'),
    path('check', views.static_view)
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from places.views import FeedbackViewSet
from users.views import UserViewSet, ObtainTokenView

router = routers.DefaultRouter()
router.register(r'feedbacks', FeedbackViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('api/', include(router.urls)),
    path('obtain_token/', ObtainTokenView.as_view()),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('places.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/models.py
from django.db import models

from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Feedback(TimestampModel):
    NEW = 1
    REVIEW = 2
    DECLINED = 3
    APPROVED = 4
    EDIT_REQUIRED = 5

    STATUSES = (
        (NEW, 'NEW'),
        (REVIEW, 'REVIEW'),
        (DECLINED, 'DECLINED'),
        (APPROVED, 'APPROVED'),
        (EDIT_REQUIRED, 'EDIT_REQUIRED'),
    )

    place = models.ForeignKey('Place', on_delete=models.CASCADE, related_name='places')
    text = models.TextField()
    author = models.ForeignKey(USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
                               related_name='feedbacks')

    status = models.PositiveSmallIntegerField(choices=STATUSES)

    approved_by = models.ForeignKey(USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
                                    related_name='approved_feedbacks')
    approved_at = models.DateTimeField(blank=True, null=True)

    @property
    def total_seats(self):
        return self.rows * self.seats

    # class Meta:
    #     unique_together = ['place', 'author']


class Place(TimestampModel):
    created_by = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='place_images/')

    def __str__(self):
        return f"{self.name}"

    @property
    def feedback_check_required(self):
        return self.feedback_set.filter(status=Feedback.NEW).exists()


class Coupon(TimestampModel):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    owners = models.ManyToManyField(through='UserCoupon', to=USER_MODEL, blank=True)
    code = models.CharField(max_length=80, blank=True, null=True)
    description = models.TextField(blank=True, null=True)


class UserCoupon(TimestampModel):
    coupon_id = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    user_id = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    used = models.BooleanField(default=False)
    used_at = models.DateTimeField(blank=True, null=True)


from django.db.models.signals import pre_save
from django.dispatch import receiver


# @receiver(pre_save)
# def my_signal(sender, **kwargs):
#     print(sender)
#     inst = kwargs['instance']
#     if inst.id is None:
#         inst.total_seats = inst.rows * inst.seats
#

places/forms.py
from django import forms

from places import models


class PlaceForm(forms.ModelForm):
    class Meta:
        model = models.Place
        fields = ('name', 'description', 'image')


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.Feedback
        fields = ('place', 'text')


class CouponForm(forms.ModelForm):
    class Meta:
        model = models.Coupon
        fields = ('code', 'description', 'price', 'place')

places/views.py
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ViewSet, ModelViewSet

from places import models, forms
from places.api.permissions import AuthorOnlyPermission
from places.api.serializers import FeedbackSerializer, PlaceSerializer


class Homepage(ListView):
    model = models.Place
    template_name = 'places/base.html'


class PlaceDetail(DetailView):
    model = models.Place


class NewPlaceView(CreateView):
    model = models.Place
    form_class = forms.PlaceForm
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class NewFeedBackView(CreateView):
    model = models.Feedback
    form_class = forms.FeedbackForm
    success_url = reverse_lazy('homepage')

    def get_initial(self):
        initial = {'place': self.kwargs.get('pk')}
        return initial

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.status = self.object.NEW
        self.object.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, 'Invalid DATA')
        return super(NewFeedBackView, self).form_invalid(form)


class FeedbacksToApprove(ListView):
    model = models.Feedback


class FeedbackApprove(View):
    def post(self, request, *args, **kwargs):
        try:
            feedback = models.Feedback.objects.get(id=self.kwargs['pk'])
        except models.Feedback.DoesNotExist:
            return HttpResponse('Invalid feedback id', status=400)
        else:
            action = self.request.POST.get('action')
            if action == 'approve':
                feedback.status = feedback.APPROVED
                feedback.author.tokens += settings.APPROVE_REWARD
                feedback.author.save()
            elif action == 'decline':
                feedback.status = feedback.DECLINED
            feedback.save()
            return HttpResponseRedirect(reverse('place_detail', kwargs={'pk': feedback.place_id}))


class PlaceEdit(UpdateView):
    model = models.Place
    form_class = forms.PlaceForm

    def get_context_data(self, **kwargs):
        """
        For Mary <3
        """
        context = super(PlaceEdit, self).get_context_data(**kwargs)
        new_places = models.Place.objects.filter(status='NEW')
        done_places = models.Place.objects.filter(status='NEW')
        done_places = models.Place.objects.filter(status='NEW')
        """
        For Matvey po bratski
        """
        ordering = self.request.GET.get('order_by')
        context.update(dict(new_places=new_places, ordering=ordering))
        return context


    def get_success_url(self):
        return reverse('place_detail', kwargs={'pk': self.object.id})


class CouponList(ListView):
    model = models.Coupon


class NewCoupon(CreateView):
    model = models.Coupon
    form_class = forms.CouponForm
    success_url = reverse_lazy('coupons')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.is_superuser:
            form.fields['place'].queryset = User.objects.filter(id=request.user.id)
        return form


class FeedbackViewSet(ModelViewSet):
    queryset = models.Feedback.objects.all()
    serializer_class = FeedbackSerializer
    permission_classes = [IsAuthenticated, AuthorOnlyPermission]

    @action(detail=True, methods=['get', 'post'])
    def mass_delete(self):
        # object = self.get_object()
        # object.approve()
        # return Response()
        pass


class PlacesAPIView(APIView):
    def get(self, request, *args, **kwargs):
        if kwargs.get('pk'):
            place = models.Place.objects.get(id=kwargs.get('pk'))
            data = PlaceSerializer(place).data
        else:
            places = models.Place.objects.filter(created_by=request.user)
            data = PlaceSerializer(places, many=True).data
        return Response(data, status=200)


def static_view(request):
    blocked_seats = [(1, 1), (1, 3), (2, 4), (5, 8)]
    cnt = {'rows': range(1, 6), 'seats': range(1, 9), 'blocked_seats': blocked_seats}
    if request.method == 'POST':
        for key, value in request.POST.items():
            if key.startswith('seat'):
                row, seat = key.split('-')[-2:]

    return render(request, 'places/test.html', cnt)

places/templates/places/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        .hr {

        }
    </style>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>NEWS | {% block title %}HOME{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {#    <a class="navbar-brand" href="#">Navbar</a>#}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
            </li>
            {% if new_feedbacks %}
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">New
                        feedbacks: {{ NEW_FEEDBACKS }}</a>
                </li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-5">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }} {{ user.tokens }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'coupons' %}">Coupons</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a> |
            <a class="nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
    </div>
</nav>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %}
    <a href="{% url 'new_place' %}" class="btn btn-success">Add new place</a>

    <div>
        {% for place in place_list %}
            <p><a href="{% url 'place_detail' place.id %}">{{ place.name }}</a></p>
            <p>{{ place.description }}</p>
            <p><img src="{{ place.image.url }}" alt="" width="200px"></p>
            {% if user == place.created_by %}
                <a href="{% url 'place_edit' place.id %}" class="btn btn-info">EDIT</a>
            {% endif %}
            <a href="{% url 'new_feedback' place.id %}" class="btn btn-warning">Add feedback</a>
            <p>Feedbacks ({{ place.feedback_set.count }})</p>
            <form action="{% url "new_feedback" place.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="place" value="{{ place.id }}">
                <label for="feedback_text__{{ place.id }}">Add feedback</label>
                <textarea name="text" id="feedback_text__{{ place.id }}" cols="30" rows="10"></textarea>
                <button>Add</button>
            </form>
        {% endfor %}
    </div>
{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
{% block extrajs %}
{% endblock %}
</body>
</html>

places/templates/places/coupon_form.html
{% extends 'places/base.html' %}


{% block title %}Create place{% endblock %}

{% block content %}
    <div class="container">
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Save</button>
        </form>
    </div>
{% endblock %}

places/templates/places/coupon_list.html
{% extends 'places/base.html' %}


{% block title %}Coupons{% endblock %}

{% block content %}
    <a href="{% url 'new_coupon' %}">ADD COUPON</a>
    <div>
        {% for object in object_list %}
            <p>{{ object.code }} | {{ object.price }}</p>
        {% empty %}
            No coupons
        {% endfor %}
    </div>

{% endblock %}

places/templates/places/feedback_form.html
{% extends 'places/base.html' %}


{% block title %}Create feedback{% endblock %}

{% block content %}
    <div class="container">
        <form action="" method="post"  enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Save</button>
        </form>
    </div>
{% endblock %}

places/templates/places/place_detail.html
{% extends 'places/base.html' %}


{% block title %}Create place{% endblock %}

{% block content %}
    <p><{{ place.name }}</p>
    <p><img src="{{ place.image.url }}" alt="" width="200px"></p>

    <p>{{ place.description }}</p>
    <a href="{% url 'new_feedback' place.id %}" class="btn btn-warning">Add feedback</a>
    <br><br>
    <p>Feedbacks</p>
    <ul>
        {% for feedback in place.feedback_set.all %}
            {% if feedback.status == feedback.APPROVED or user.id == place.created_by.id %}
                <li>
                    {% if feedback.status == feedback.NEW %}
                        <form action="{% url 'moderate_feedback' feedback.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="approve">
                            <button class="btn btn-success">V</button>
                        </form>
                        <form action="{% url 'moderate_feedback' feedback.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="decline">
                            <button class="btn btn-danger">X</button>
                        </form>
                    {% endif %}
                    {{ feedback.author.username }}: {{ feedback.text }}
                    {% if feedback.status == feedback.DECLINED %}( declined ){% endif %}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

places/templates/places/place_form.html
{% extends 'places/base.html' %}


{% block title %}Create place{% endblock %}

{% block content %}
    <div class="container">
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Save</button>
        </form>
    </div>
{% endblock %}

places/templates/places/test.html
{% extends 'places/base.html' %}

{% load places_extra %}

{% block content %}

    <form action="" class="hall-form" method="post">
        {% csrf_token %}
        {% for row in rows %}
            <div class="d-flex">
                {% for seat in seats %}
                    <div class="checkbox-wrap">
                        <label for="seat-{{ row }}-{{ seat }}">{{ row }}{{ seat }}</label>
                        <input id="seat-{{ row }}-{{ seat }}"
                               {% if blocked_seats|check_row:row|check_seat:seat %}disabled=""{% endif %}
                               name="seat-{{ row }}-{{ seat }}" type="checkbox"/>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <button>Submit</button>
    </form>
    <form action="matvey ordering">
        <select name="order_by" id="">
            <option value="price"> Price</option>
            <option value="time"{% if ordering == 'time' %} selected{% endif %}> Time</option>
        </select>
                <button>sort</button>

    </form>
{% endblock %}